# Generated by Django 3.0.8 on 2020-11-01 18:27

from django.db import migrations, models
import django.utils.timezone
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('vectors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vector',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='vector',
            name='uploaded',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vector',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
