# Generated by Django 3.0.8 on 2020-11-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vectors', '0002_auto_20201101_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='Featured',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('tag', models.CharField(max_length=100)),
                ('order', models.IntegerField()),
            ],
        ),
    ]
