# Generated by Django 3.0.8 on 2021-12-13 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vectors', '0003_featured'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featured',
            options={'ordering': ['order']},
        ),
    ]
