# Generated by Django 3.0.8 on 2021-12-14 09:52

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vectors', '0004_auto_20211213_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='vector',
            name='colored_svg',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='vector',
            name='fill_color',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, samples=None),
        ),
        migrations.AddField(
            model_name='vector',
            name='stroke_color',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, samples=None),
        ),
    ]
