# Generated by Django 3.2.10 on 2021-12-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vectors', '0005_auto_20211214_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featured',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vector',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
