# Generated by Django 3.2.10 on 2021-12-17 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vectors', '0006_auto_20211217_1503'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vector',
            options={'ordering': ['id']},
        ),
    ]
