# Generated by Django 3.2.10 on 2021-12-27 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vectors', '0008_rename_name_vector_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='vector',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
