# Generated by Django 4.1.4 on 2022-12-20 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vectors", "0009_vector_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="vector",
            name="search_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
