# Generated by Django 4.1.4 on 2022-12-20 18:29

from django.db import migrations


def populate_search_text(apps, schema_editor):
    if schema_editor.connection.alias != 'default':
        return

    Vector = apps.get_model("vectors", "Vector")
    TaggedItems = apps.get_model('taggit', 'TaggedItem')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    ct = ContentType.objects.get(app_label="vectors", model="vector")
    for v in Vector.objects.all():
        tagged_items = TaggedItems.objects.filter(content_type_id=ct.id, object_id=v.id)
        v.search_text = " ".join(i.tag.name for i in tagged_items)
        v.save()


class Migration(migrations.Migration):

    dependencies = [
        ("vectors", "0010_vector_search_text"),
    ]

    operations = [
        migrations.RunPython(populate_search_text),
    ]
