# Generated by Django 4.1.4 on 2022-12-20 22:33

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension

class Migration(migrations.Migration):

    dependencies = [
        ("vectors", "0011_populate_search_text"),
    ]

    operations = [
        TrigramExtension()
    ]
