# Generated by Django 4.1.4 on 2023-03-25 16:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vectors", "0012_install_pg_trgm"),
    ]

    operations = [
        migrations.AlterField(
            model_name="featured",
            name="order",
            field=models.IntegerField(default=999),
        ),
    ]
