# Generated by Django 4.1.4 on 2023-03-25 19:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vectors", "0013_alter_featured_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="featured",
            name="tag",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
