# Generated by Django 4.1.4 on 2023-03-25 19:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vectors", "0014_alter_featured_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="featured",
            name="name",
            field=models.CharField(default="-- name needed --", max_length=100),
            preserve_default=False,
        ),
    ]
