# Generated by Django 4.1.4 on 2023-07-15 16:24

from django.contrib.postgres.operations import CreateExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vectors", "0015_alter_featured_name"),
    ]

    operations = [
        CreateExtension("unaccent"),
        migrations.RunSQL(
            """
            DROP TEXT SEARCH CONFIGURATION IF EXISTS simple_unaccent cascade;
            CREATE TEXT SEARCH CONFIGURATION simple_unaccent ( COPY = pg_catalog.simple );
            ALTER TEXT SEARCH CONFIGURATION simple_unaccent
            ALTER MAPPING FOR hword, hword_part, word WITH unaccent, simple;
            """
        ),
    ]
