# Generated by Django 4.2.3 on 2023-09-10 11:00

import constrainedfilefield.fields.file
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vectors", "0017_vector_colored_gif_vector_gif_alter_vector_svg_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vector",
            name="colored_gif",
            field=constrainedfilefield.fields.file.ConstrainedFileField(
                blank=True,
                content_types=["image/gif"],
                mime_lookup_length=4096,
                null=True,
                upload_to="",
            ),
        ),
        migrations.AlterField(
            model_name="vector",
            name="colored_svg",
            field=constrainedfilefield.fields.file.ConstrainedFileField(
                blank=True,
                content_types=["image/svg+xml"],
                mime_lookup_length=4096,
                null=True,
                upload_to="",
            ),
        ),
        migrations.AlterField(
            model_name="vector",
            name="gif",
            field=constrainedfilefield.fields.file.ConstrainedFileField(
                blank=True,
                content_types=["image/gif"],
                mime_lookup_length=4096,
                null=True,
                upload_to="",
            ),
        ),
        migrations.AlterField(
            model_name="vector",
            name="svg",
            field=constrainedfilefield.fields.file.ConstrainedFileField(
                blank=True,
                content_types=["image/svg+xml"],
                mime_lookup_length=4096,
                null=True,
                upload_to="",
            ),
        ),
    ]
